### ISSUE TITLE
[Setup] Error when trying to get a token

### ISSUE THREAD

**Issue by RSant0s** [headspinio/appium-tizen-tv-driver#120]
Hi team,

I'm facing a problem on the step : 
`appium driver run tizentv pair-remote`

I wasn't able to get the token and the following error was triggered.

``` 
RMS@RMS-MacBook-Pro tizen % sdb devices                                           
List of devices attached 
10.0.0.43:26101         device          HG49EJ690U
RMS@RMS-MacBook-Pro tizen % sdb connect 10.0.0.43                                 
10.0.0.43:26101 is already connected
RMS@RMS-MacBook-Pro tizen % appium driver run tizentv pair-remote --host 10.0.0.43
[STDERR] 
[STDERR] /Users/RMS/.appium/node_modules/appium-tizen-tv-driver/node_modules/@headspinio/tizen-remote/lib/tizen-remote.js:795
[STDERR]       throw new Error(`Could not get token; server responded with: ${format('%O', res)}`);
[STDERR]             ^
[STDERR] Error: Could not get token; server responded with: {
[STDERR]   data: { clients: [ [Object] ], id: '555ae14d-bc28-419c-9d21-576c53c016f8' },
[STDERR]   event: 'ms.channel.connect'
[STDERR] }
[STDERR]     at TizenRemote.getToken (/Users/RMS/.appium/node_modules/appium-tizen-tv-driver/node_modules/@headspinio/tizen-remote/lib/tizen-remote.js:795:13)
[STDERR]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[STDERR]     at pairRemote (/Users/RMS/.appium/node_modules/appium-tizen-tv-driver/lib/rc-pair.js:14:19)
[STDERR]     at main (/Users/RMS/.appium/node_modules/appium-tizen-tv-driver/lib/rc-pair.js:68:5)
✖ Encountered an error when running 'pair-remote': Process ended with exitcode 1 (cmd: '/usr/local/bin/node ./build/lib/rc-pair.js --host 10.0.0.43')
RMS@RMS-MacBook-Pro tizen % 
```

**Appium Version:** 2.0.0-beta.46

Can you please help me ?

**Comment by jlipps** [comment]
@boneskull any ideas?

**Comment by boneskull** [comment]
@RSant0s @jlipps I'll look into this, but the driver now retrieves and persists a token automatically on first connection, so you may not need to run `pair-remote` at all.

**Comment by KazuCocoa** [comment]
Potentially this was once the popup was denied. I made a few possible suggestions for the remote command
