### ISSUE TITLE
server-side error occurred while processing the command: Could not find a driver for automationName 'Appium' and platformName TizenTV'

### ISSUE THREAD

**Issue by gopi-chand** [headspinio/appium-tizen-tv-driver#25]
Issue:
Could not find a driver for automationName 'Appium' and platformName TizenTV'

Setup details:
Have added this appium-tizen-tv-driver to appium@2.0.0-beta.40 version by using following commend
`appium driver install --source=npm appium-tizen-tv-driver`

Used  `Appium-Python-Client 2.6.0 `
executed following  code

Code
```
from appium import webdriver
import time
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723',
    desired_capabilities={
        "platformName": "TizenTV",
        'deviceName': 'SamsungTV',
        'deviceAddress': 'IP address ',
        'deviceMac' : 'MAC address,
        'udid': 'UUIDL',
        'appPackage': 'PackageID',
        'chromedriverExecutable' : 'Path'
        'isDeviceApiSsl': 'True',
        'app': 'KaveriOnTizen',
        'automationName': 'Appium'

    })

print(driver.press_button("down")) 
  
```
```
Console output:
/Users/agopichand/projects/appium/venv/bin/python /Users/agopichand/projects/appium/connect.py
Traceback (most recent call last):
  File "/Users/agopichand/projects/appium/connect.py", line 3, in <module>
    driver = webdriver.Remote(
  File "/Users/agopichand/projects/appium/venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py", line 229, in __init__
    super().__init__(
  File "/Users/agopichand/projects/appium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/agopichand/projects/appium/venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py", line 319, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "/Users/agopichand/projects/appium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/Users/agopichand/projects/appium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Appium' and platformName TizenTV'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Appium' and platformName TizenTV'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:956:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:428:35)
```

**Comment by jlipps** [comment]
automation name should be `TizenTV` as you saw in the driver installation output
