### ISSUE TITLE
Tizen App installation, run and uninstallation is not working on appium-tizen-tv-driver duo to the wrong paramer -s

### ISSUE THREAD

**Issue by gopi-chand** [headspinio/appium-tizen-tv-driver#26]
Issue:
Tizen App installation, run and uninstallation is not working on appium-tizen-tv-driver due to the wrong parameter '-s'

Expected parameter for TIZEN CLI commend 

tizen install -n name  -t UUID -- ~/path
tizen run -p packageName -t UUID
tizen uninstall -p packageName -t UUID

Verified above commends on tizen CLI, those are working 

wrong commends with -s parameter
Administrators-MacBook-Pro:bin <username >$ tizen run -p <packageName>  -s  <UUID>
There is no <UUID> target.
Can not get the target option.

Correct commend wiht -t parameter
Administrators-MacBook-Pro:bin <userName>$ tizen run  -p <packageName>  -t  <UUID>
Launching the Tizen application...
--------------------
Platform log view
--------------------
... successfully launched pid = 1049 with debug 0
Tizen application is successfully launched.

Setup details:
Have added this appium-tizen-tv-driver to appium@2.0.0-beta.40 version by using following commend
appium driver install --source=npm appium-tizen-tv-driver

Used Appium-Python-Client 2.6.0

executed following code

Desired capabilities:
```
driver = webdriver.Remote(
    command_executor='http://127.0.0.1:4723',
    desired_capabilities={
        "platformName": "TizenTV",
        'deviceName': 'SamsungTV',
        'deviceAddress': 'Device IP',
        'deviceMac' : 'Device Mac Address,
        'udid': 'uuid',
        'appPackage': 'app package name',
        'chromedriverExecutable': '/path,
        'isDeviceApiSsl': True,
        'app': '/path',
        'automationName': 'TizenTV',
        'noReset': True
    })
```
Console output:
```
Traceback (most recent call last):
  File "/Users/username/projects/appium/connect.py", line 3, in <module>
    driver = webdriver.Remote(
  File "/Users/username/projects/appium/venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py", line 229, in __init__
    super().__init__(
  File "/Users/username/projects/appium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/username/projects/appium/venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py", line 319, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "/Users/username/projects/appium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/Users/username/projects/appium/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Command '/Users/username/tizen-studio/tools/ide/bin/tizen install -n ~/projects/path  -s UUID' exited with code 1. Stdout was: 'There is no UUID  target. Total time: 00:00:00.469
'. Stderr was: ''
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Command '/Users/username/tizen-studio/tools/ide/bin/tizen install -n ~/projects/path -s UUID' exited with code 1. Stdout was: 'There is no UUID target. Total time: 00:00:00.469
'. Stderr was: ''
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:956:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:428:35)

```
Tizen CLI 2.5.25 version

Please fix this issue as soon as possible.

**Comment by jlipps** [comment]
```
~/C/g/h/appium-tizen-tv-driver ❯❯❯ tizen run                                                                                                                                                                                                                                                                        

Error: Option "-p (--pkgid)" is required

Usage:  tizen run [args]
 -- <working directory>                  Specify where the base directory is
                                          for the command
 -T (--type) package type (app or utc)   Specify if the package is app or
                                          native unit test
 -h (--help)                             Show the detailed description of a
                                          given command.
 -o (--out) Output folder to copy unit   Specify the output folder to copy
 test and coverage files                 unit test and coverage artifacts
 -p (--pkgid) <package id>               Specify the Tizen package ID installed
                                          on the target.
 -s (--serial) <serial>                  Specify the serial to run the package.
 -t (--target) <target>                  Specify the target name to run the
                                          package.
```

we are using `-s` for the serial ID, this is the info which should be sent in for the `appium:udid` cap. Did you try this? It seems like you sent in `UUID`, which is not correct.

**Comment by gopi-chand** [comment]
Got confused with Serial - s when provide Device IP and port it is working.
