### ISSUE TITLE
Failed to launch my-app as debug mode. It might not be debuggable, or the device condition was weird.

### ISSUE THREAD

**Issue by mlopezuno** [headspinio/appium-tizen-tv-driver#685]
Hi, I have started using the appium-tizen driver and I've been able to get unstuck on many issues I encountered, right now I am finally able to load my-app in the TV using the driver but my tests don't run, at the end I get a message like this: 

```
Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Failed to launch my-app as debug mode. It might not be debuggable, or the device condition was weird. Original error: Command '/Users/user/tizen-studio/tools/sdb -s <my-ip>\:26101 shell 0 debug my-app' exited with code 1. Stdout was: ''. Stderr was: 'closed '
[0]     at TizenTVDriver.setupDebugger (/Users/user/path/repo/node_modules/appium/node_modules/appium-tizen-tv-driver/lib/driver.js:501:15)
[0]     at TizenTVDriver.createSession (/Users/user/path/repo/node_modules/appium/node_modules/appium-tizen-tv-driver/lib/driver.js:420:30)
[0]     at AppiumDriver.createSession (/Users/user/path/repo/node_modules/appium/lib/appium.js:739:35)
```

Does someone know how can I fix this?
It looks like I have to run my app in debug mode.

**Comment by KazuCocoa** [comment]
Could you share the full appim server log?
Also, could the app run with `sdb -s <my-ip>\:26101 shell 0 debug my-app` without this driver?

I observed the debug mode run could fail to start for some reason. (TV internal) If the error is kind of random failure, https://github.com/headspinio/appium-tizen-tv-driver/pull/676 will help to improve with retry logic. If your app was not debggable one, `appium:rcMode` as `remote`  and `appium:rcOnly` will also help. They will not run chromedriver but it does not require debuggable app. https://github.com/headspinio/appium-tizen-tv-driver/tree/main/packages/appium-tizen-tv-driver#press-key is available for the mode.
https://github.com/headspinio/appium-tizen-tv-driver/tree/main/packages/appium-tizen-tv-driver

**Comment by HarishIfocus** [comment]
@KazuCocoa 
even i am facing same Issue sharing the  full appim server logs Here 

[AppiumDriver@0d30] Appium v2.11.5 creating new TizenTVDriver (v0.13.1) session
[AppiumDriver@0d30] Checking BaseDriver versions for Appium and TizenTVDriver
[AppiumDriver@0d30] Appium's BaseDriver version is 9.11.5
[AppiumDriver@0d30] TizenTVDriver's BaseDriver version is 9.11.5
[TizenTVDriver@3e2c] 
[TizenTVDriver@3e2c] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "TizenTV",
    "appium:sendKeysStrategy": "proxy",
    "appium:appId": "NHQoULJE2m.toggleSg",
    "appium:newCommandTimeout": 180000,
    "appium:chromedriverExecutable": "/Users/ifocus/Downloads/chromedriver",
    "appium:automationName": "TizenTV",
    "appium:noReset": false,
    "appium:udid": "10.192.147.38:26101",
    "appium:rcMode": "remote",
    "appium:deviceHost": "10.192.147.38:26101",
    "appium:deviceName": "10.192.147.38:26101",
    "appium:fastReset": true,
    "appium:appPackage": "NHQoULJE2m.toggleSg"
  },
  "firstMatch": [
    {}
  ]
}
[TizenTVDriver@3e2c] The following provided capabilities were not recognized by this driver:
[TizenTVDriver@3e2c]   appId
[TizenTVDriver@3e2c]   deviceHost
[TizenTVDriver@3e2c]   fastReset
[06f7252f][TizenTVDriver@3e2c] Session created with session id: 06f7252f-9c3a-4b1f-9172-4b12b30db103
[06f7252f][TizenTVDriver] No udid and/or deviceAddress provided; attempting to derive from deviceName "10.192.147.38:26101"
[06f7252f][TizenTVDriver] Setting deviceAddress to "10.192.147.38"
[06f7252f][TizenTVDriver] Getting capabilities on '10.192.147.38:26101'
[06f7252f][TizenTVDriver] Running command: /home/rashmi/tizen-studio/tools/sdb -s 10.192.147.38:26101 capability
[06f7252f][TizenTVDriver] The Tizen platform version is 4.0
[06f7252f][TizenTVDriver] Received rcKeypressCooldown of type undefined
[06f7252f][TizenTVDriver] Attempt to launch existing apps from candidates.
[06f7252f][TizenTVDriver] Running tizen app 'org.tizen.browser' on device '10.192.147.38:26101'
[06f7252f][TizenTVDriver] Running command: /home/rashmi/tizen-studio/tools/ide/bin/tizen run -p org.tizen.browser -s 10.192.147.38:26101
[06f7252f][TizenTVDriver] org.tizen.browser started successfully
[06f7252f][TizenTVDriver] Listing apps installed on '10.192.147.38:26101'
[06f7252f][TizenTVDriver] Running command: /home/rashmi/tizen-studio/tools/sdb -s 10.192.147.38:26101 shell 0 applist
[06f7252f][TizenTVDriver] There are 210 apps installed
[06f7252f][TizenTVDriver] Starting NHQoULJE2m.toggleSg in debug mode on 10.192.147.38:26101
[06f7252f][TizenTVDriver] Running command: /home/rashmi/tizen-studio/tools/sdb -s 10.192.147.38:26101 shell 0 debug NHQoULJE2m.toggleSg
[9de43e7e][TizenTVDriver] Cleaning up any ports which have been forwarded
[9de43e7e][AppiumDriver@0d30] Event 'newSessionStarted' logged at 1732772687294 (13:44:47 GMT+0800 (Singapore Standard Time))
[9de43e7e][AppiumDriver@0d30] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Failed to launch NHQoULJE2m.toggleSg as debug mode. It might not be debuggable, or the device condition was weird. Original error: Command '/home/rashmi/tizen-studio/tools/sdb -s 10.192.147.38\:26101 shell 0 debug NHQoULJE2m.toggleSg' timed out after 240000ms. Stdout was: ''. Stderr was: ''
    at TizenTVDriver.setupDebugger (/home/rashmi/node_modules/appium-tizen-tv-driver/lib/driver.js:501:15)
    at TizenTVDriver.createSession (/home/rashmi/node_modules/appium-tizen-tv-driver/lib/driver.js:420:30)
    at AppiumDriver.createSession (/home/rashmi/.nvm/versions/node/v16.20.2/lib/node_modules/appium/lib/appium.js:739:35)
[HTTP] <-- POST /session - - ms - -

**Comment by KazuCocoa** [comment]
> [9de43e7e][AppiumDriver@0d30] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Failed to launch NHQoULJE2m.toggleSg as debug mode. It might not be debuggable, or the device condition was weird. Original error: Command '/home/rashmi/tizen-studio/tools/sdb -s 10.192.147.38:26101 shell 0 debug NHQoULJE2m.toggleSg' timed out after 240000ms. Stdout was: ''. Stderr was: ''


It usually indicate the `sdb` command and shell provided by Tizen and TV itself didn't respond over the timeout.  It is out of control by Appium driver side. Only thing I could suggest is https://github.com/headspinio/appium-tizen-tv-driver/blob/main/packages/appium-tizen-tv-driver/CHANGELOG.md#0140-2024-10-29

**Comment by KazuCocoa** [comment]
I observed the `debug` command failed to launch the app randomly. The reason was unknown as us. Retry helped in the past, so https://github.com/headspinio/appium-tizen-tv-driver/blob/main/packages/appium-tizen-tv-driver/CHANGELOG.md#0140-2024-10-29 introduced retry logic.

Closing this issue for now since the retry is current best knowledge thing to improve this random failure by TV side.
